config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'dashboard#index'

  resources :spaces do
    resources :content_types do
      resources :entries
    end
  end

end

app/models/content_type.rb
class ContentType < ActiveRecord::Base
    belongs_to :space
    has_many :entry

    validates :name, presence: true, length: { maximum: 64 }, uniqueness: { case_sensitive: false }
    validates :space_id, presence: true

    # Creates a Hash from the JSON-encoded 'fields' attribute
    def fields_decoded
        ActiveSupport::JSON.decode(self.fields)["fields"]
    end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :content_type
  belongs_to :space

  # CHANGE THIS LATER! No real name attribute! Check the comment below.
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }, uniqueness: { case_sensitive: false }

  # This is ok
  validates :fields, presence: true

  # TODO:
  # Write own validation that checks for the self-set primary key.
  # The primary key is not known to the DB or to the Vanilla Rails, it's inside of the ContentType's fields JSON Tree.
  # Right now, we use a faux name attribute simply called "name"
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_many :content_types
  has_many :entries

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content_types_controller.rb
class ContentTypesController < ApplicationController
    def new
        @space = Space.find(params[:space_id])
        @content_type = ContentType.new(space_id: @space.id)
    end

    def create
        @space = Space.find(params[:space_id])
        @content_type = @space.content_types.build(content_type_params)

        if @content_type.save
            redirect_to @content_type.space
        else
            render :new
        end
    end

    def show
        @space = Space.find(params[:space_id])
        @content_type = ContentType.find(params[:id])
        @entries = @content_type.entry.all
    end

    def index
        @content_type = ContentType.all
    end

    def edit
        @content_type = ContentType.find(params[:id])
    end

    def update
        @content_type = ContentType.find(params[:id])

        if @content_type.update(content_type_update_params)
            redirect_to space_content_type_path(@content_type.space.id, @content_type.id)
        else
            render :edit
        end
    end

    def destroy
    end

    private
        def content_type_params
            params.require(:content_type).permit(:name, :fields)
        end

        def content_type_update_params
            params.require(:content_type).permit(:name, :fields)
        end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @spaces = Space.all
    @entries = Entry.all
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    def new
        @content_type = ContentType.find(params[:content_type_id])

        # Create Fields based on Content Type's fields attribute
        # This will need to use JSON::decode later on.
        # @fields = ActiveSupport::JSON.decode(@content_type.fields || ActiveSupport::JSON.encode('{ { "name": "name", "type": "text" }, { "name": "password", "type": "text" } }'))
        # @hash = { fields: [{name: 'name', type: 'text'}, {name: 'password', type: 'text'}] }
        # @json = ActiveSupport::JSON.encode(@hash)
        # @fields = ActiveSupport::JSON.decode(@json)
        @entry = Entry.new
    end

    def create
        @content_type = ContentType.find(params[:content_type_id])
        # Create an Entry by building one via the @content_type's methods
        @entry = @content_type.entries.build(name: entry_params[:name], fields: ActiveSupport::JSON.encode(entry_params[:fields]))

        if @entry.save
            redirect_to show_space_content_type_entry(space_id: @entry.content_type.space.id, content_type_id: @entry.content_type.id, id: @entry.id)
        else
            render :new
        end
    end

    def index
        @entries = Entry.all
    end

    def show
        @entry = Entry.find(params[:id])
    end

    def edit

    end

    def update

    end

    def destroy

    end

    private
        def entry_params
            params.require(:entry).permit(:name, :fields)
        end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  def new
    @space = Space.new
  end

  def create
    @space = Space.create(space_params)

    if @space.save
      redirect_to @space
    else
      render :new
    end
  end

  def show
    @space = Space.find(params[:id])
  end

  def edit
    @space = Space.find(params[:id])
  end

  def index
    @spaces = Space.all
  end

  def update
  end

  def destroy
  end

  private
    def space_params
      params.require(:space).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_space
        Space.last || Space.new
    end

    def link_back(text = 'back', css: 'pure-button')
        link_to text, :back, class: css
    end

    # This methods turns the JSON strings into real HTML Input Elements
    # Expects a hash containing a Name and a Field Type, e.g. 'select' or 'text'
    def field_transform(name, field_type)
        case field_type
            when 'text'
                text_field_tag name
            when 'textbox'
                text_area_tag name
            when 'password'
                password_field_tag name
            when 'email'
                email_field_tag name
            when 'select'
                "not yet implemented"
            else
                puts "LOL"
        end
    end
end

app/helpers/content_type_helper.rb
module ContentTypeHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/entry_helper.rb
module EntryHelper

end

app/helpers/space_helper.rb
module SpaceHelper
end

app/views/content_types/edit.html.erb
<div class="responsive-form bg-white">
    <div class="r-box">
        <h1>Edit Content Type <b>"<%= @content_type.name %>"</b></h1>
        
        <%= form_for @content_type, url: space_content_type_path(@content_type.space.id, @content_type.id), method: :patch, html: { class: 'pure-form pure-form-stacked' } do |f| %>

            <fieldset>
                <h3>Name / ID</h3>
                <%= f.text_field :name, value: @content_type.name %>
            </fieldset>


            <fieldset>
                <h3>Fields</h3>
                <% @content_type.fields_decoded.each do |field| %>
                    <%= label_tag field["name"] %>
                    <%= field_transform field["name"], field["type"] %>
                <% end %>
            </fieldset>


            <fieldset>
                <%= link_back 'cancel' %>
                <%= f.submit 'save changes', class: 'pure-button pure-button-primary' %>
            </fieldset>

        <% end %>

    </div>
</div>

app/views/content_types/index.html.erb
<h1>Content Types</h1>

<% if @content_types %>

<% else %>
    <h2>Yikes!</h2>
    <p>You haven't created any content types yet.</p>
    <p>Click <%= link_to 'here', new_content_type_path %> to create your first Content Type!</p>
<% end %>

app/views/content_types/new.html.erb
<div class="responsive-form bg-white">
    <div class="r-box">
        <h1>Create a new Content Type for the Space "<%= @space.name %>"</h1>

        <% if @content_type.errors.any? %>
            <ul class="x-errors">
            <% @content_type.errors.full_messages.each do |error| %>
                <li><%= error %></li>
            <% end %>
            </ul>
        <% end %>

        <%= form_for @content_type, url: space_content_types_path, html: { class: 'pure-form pure-form-stacked' } do |f| %>
            <legend>Preparation</legend>
            <p>
                Enter the name of your new Content Type.
                <br>
                This name will act as it's <b>ID</b> ( <a href="#">@doc/api/id</a> ).
            </p>
            <fieldset>
                <%= f.label :name %>
                <%= f.text_field :name, placeholder: 'e.g. "Articles"' %>
            </fieldset>

            <fieldset>
                <h3>Fields</h3>

                <%= f.text_area :fields, value: '{"name": "json", "date": "yesterday" }' %>
            </fieldset>

            <fieldset>
                <%= link_to 'cancel', :back, class: 'pure-button' %>
                <%= f.submit 'Create Content Type', class: 'pure-button pure-button-primary', style: 'float: right' %>
            </fieldset>
        <% end %>  
    </div>
</div>

app/views/content_types/show.html.erb
<div class="responsive-form bg-white">
    <div class="r-box">
        <h1><%= @space.name %></h1>
        <h2>Content Type: <b><%= @content_type.name %></b></h2>
        <!-- TODO: Optional Link to Company's Documentation for this Content Type -->
        <p>
            Not sure what to do?
            <a href="#">See the Documentation about <%= @content_type.name %>.</a>
        </p>
        <hr>

        <h2>Fields</h2>
        <div>
            <% @content_type.fields_decoded.each do |field| %>
                <div style="margin-bottom: 1em">
                    <p style="font-size: 1.1rem">
                        <%= field['name'] %>
                        <br /><small>Type: <%= field['type'] %></small>
                    </p>
                </div>
            <% end %>

        </div>

        <div>
            <% if @space.content_types.count > 0 %>
                <!-- TODO: Add a Dropdown here (once you click on the link), so you get a PROPER content_type_id  -->
                <%= link_to "Back to #{@content_type.space.name}", space_path(@content_type.space.id), class: 'pure-button' %>
                <%= link_to 'Create new Entry', new_space_content_type_entry_path(space_id: @content_type.space.id, content_type_id: @content_type.id), class: 'pure-button pure-button-primary', style: "float: right" %>
            <% end %>
        </div>
    </div>
</div>

app/views/dashboard/index.html.erb
<div class="pure-g">

    <% if @spaces.count > 0 %>
    <div class="pure-u-1 pure-u-md-1-6">
        <div class="r-box">
            <h3>Spaces</h3>
            <ul class="spaces-list">
            <% @spaces.each do |space| %>
                <li><%= link_to space.name, space %></li>
            <% end %>
            </ul>
        </div>
    </div>
    <% else %>
        <p>No Spaces found.</p>
        <p>
            <%= link_to 'Create your first Space', new_space_path %>
        </p>
    <% end %>

    <div class="pure-u-1 pure-u-md-2-3">
        <div class="splash">
            <div class="l-box">
                <div class="splash-logo" style="text-align: center; display: block;">
                    <%= image_tag 'contender-logo.png', class: "lg-only" %>
                    <h1>Contender - Dashboard</h1>
                </div>
                
                <div class="pure-g">

                    <div class="pure-u-1 pure-u-lg-1-3">
                        <div class="l-box">
                            <h3>Quick Actions</h3>
                            <ul class="no-p">
                                <%= link_to 'Create a new Space', new_space_path %>
                            </ul>
                        </div>
                    </div>

                    <% if @spaces.count > 0 && @spaces.first.content_types.count > 0 %>
                    <div class="pure-u-1 pure-u-lg-1-3">
                        <div class="l-box">
                            <h3>Latest Entries</h3>
                            <% if @entries.count > 0 %>

                            <% else %>
                                <p>No Entries found.</p>
                                <p>
                                    <%= link_to 'Create your first Entry', new_space_content_type_entry_path(current_space, current_space.content_types.first) %>
                                </p>
                            <% end %>
                        </div>
                    </div>
                    <% end %>

                    <div class="pure-u-1 pure-u-lg-1-3">
                        <div class="l-box">
                            <h3>User Management</h3>
                            <div class="dasher">
                                <div class="l-box">
                                    <h4>Involved Users</h4>
                                    <% User.all.each do |user| %>
                                        <%= user.email %>
                                    <% end %>
                                </div>
                            </div>
                            <div class="dasher">
                                <div class="l-box">
                                    <form class="pure-form">
                                        <legend>Invite a new User</legend>
                                        <br />
                                        <input type="text" class="pure-input" placeholder="user@domain.com">
                                        <button type="submit" class="pure-button pure-button-primary">send invite</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="pure-u-1 pure-u-md-1-6">
        <div class="r-box">
            <h3>Help</h3>
            <ul>
                <li><a href="#">Getting Started</a></li>
                <li><a href="#">User Management</a></li>
                <li><a href="#">JSON Encoding</a></li>
                <li><a href="#">Product Plans</a></li>
                <li><a href="#">Documentation</a></li>
            </ul>
        </div>
    </div>

</div>

app/views/entries/new.html.erb
<!-- Entry#New -->
<div class="responsive-form bg-white">
    <div class="r-box">
        <h1>Create <b>new</b> <%= link_to @content_type.name, edit_space_content_type_path(space_id: @content_type.space.id, id: @content_type.id) %> in <%= link_to @content_type.space.name, @content_type.space %></h1>

        <% if @entry.errors.any? %>
            <ul class="x-errors">
            <% @entry.errors.full_messages.each do |error| %>
                <li><%= error %></li>
            <% end %>
            </ul>
        <% end %>


        <%= form_for @entry, url: space_content_type_entries_path, html: { class: "pure-form pure-form-stacked"} do |f| %>
            
            <%= f.label :name, "Entry's ID" %><small style="color: #f44">NOTE: This will be replaced by a user-chosen entry later in development</small>
            <%= f.text_field :name, placeholder: "Entry's ID" %>

            <% @content_type.fields_decoded.each do |field| %>
                <%= label_tag field["name"] %>
                <%= field_transform(field["name"], field["type"]) %>
            <% end %>

            <fieldset>
                <%= link_back %>
                <%= submit_tag "Save #{@content_type.name}", class: "pure-button pure-button-primary" %>
            </fieldset>

        <% end %>
    </div>
</div>

app/views/entries/show.html.erb
<div class="responsive-form bg-white">
    <div class="r-box">
        <h3><%= @entry.content_type %></h3>
        <h1>Entry <b><%= @entry.name %></b></h1>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contender</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lte IE 8]>
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
    <!--<![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    <%= render "shared/header" %>
    <div class="l-box-page">
        <%= yield %>
    </div>

</html>

app/views/shared/_header.html.erb
<div class="x-menu-horizontal">
    <div class="x-menu-logo">
        <%= link_to root_path do %>
            <%= image_tag 'contender-logo-small.png', class: 'x-menu-logo-img pureimg' %>
            Contender
        <% end %>
    </div><ul>
    <% if user_signed_in? %>
        <li>
            <%= link_to current_space, class: 'active' do %>
                Active Space: <%= current_space.name %>
            <% end %>
        </li>
        <li><%= link_to 'Spaces', spaces_path %></li>
        <li><%= link_to ' All Entries', root_path %></li>
    <% else %>
        <li><a href="#">Info</a></li>
    <% end %>
    </ul>

    <ul class="float-right">
    <% if user_signed_in? %>
        <li><%= link_to current_user.email %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

    <% else %>
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path, class: 'btn-sign-in' %></li>
    <% end %>    
    </ul>

</div>

app/views/spaces/create.html.erb
<h1>Space#create</h1>
<p>Find me in app/views/space/create.html.erb</p>

app/views/spaces/destroy.html.erb
<h1>Space#destroy</h1>
<p>Find me in app/views/space/destroy.html.erb</p>

app/views/spaces/edit.html.erb
<div class="responsive-form bg-white">
    <div class="r-box">
        <h1>Edit Space <b>"<%= @space.name %>"</b></h1>
        
        <%= form_for @space, method: :patch, html: { class: 'pure-form pure-form-stacked' } do |f| %>

            <fieldset>
                <h3>Name / ID</h3>
                <%= f.text_field :name %>
            </fieldset>

            <fieldset>
                <%= link_back 'cancel' %>
                <%= f.submit 'save changes', class: 'pure-button pure-button-primary' %>
            </fieldset>

        <% end %>

    </div>
</div>

app/views/spaces/index.html.erb
<div class="responsive-form">
    <div class="r-box">

        <h1>Spaces</h1>

        <% if @spaces.count > 0 %>
            <ul class="spaces-list">
                <% @spaces.each do |space| %>
                    <li>
                        <%= link_to space.name, space %>
                        <ul class="actions">
                            <!-- TODO: Make this a Dropdown Element -->
                            <li>
                                <%= link_to edit_space_path(id: space.id) do %> 
                                    <%= fa_icon "gear", class: 'fa-fw' %>
                                <% end %>
                            </li>

                            <li>
                                <%= link_to new_space_content_type_path(space_id: space.id) do %>
                                    <%= fa_icon "file", class: 'fa-fw', style: 'color: #0078E7' %>
                                <% end %>
                            </li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        <% else %>
            <p>Sorry, no spaces found.</p>
            <p>You can <%= link_to 'Create a new Space here', new_space_path %>.</p>
        <% end %>

    </div>
</div>

app/views/spaces/new.html.erb
<div class="responsive-form bg-white">
    <div class="r-box">
        <h1>Create a new Space</h1>
        <p>This <i>Holy Magical Wizard</i> will help you to create a new Space.</p>

        <% if @space.errors.any? %>
            <ul class="x-errors">
            <% @space.errors.full_messages.each do |error| %>
                <li><%= error %></li>
            <% end %>
            </ul>
        <% end %>

        <%= form_for @space, html: { class: 'x-form pure-form pure-form-stacked' } do |f| %>

            <fieldset>
                <%= f.text_field :name, placeholder: 'Space Name' %>
            </fieldset>

            <fieldset>
                <%= f.submit 'submit' , class: 'pure-button pure-button-primary' %>
                <%= link_to 'cancel', :back,  class: 'pure-button' %>
            </fieldset>

        <% end %>
    </div>
</div>

app/views/spaces/show.html.erb
<div class="responsive-form">
    <div class="r-box">
        <h1>Space ID: <b><%= @space.name %></b></h1>
        <%= link_to 'Create new Content Type', new_space_content_type_path(@space), class: 'pure-button pure-button-primary' %>
        
            <% if @space.content_types.count > 0 %>
                <!-- TODO: Add a Dropdown here (once you click on the link), so you get a PROPER content_type_id  -->
                <%= link_to 'Create new Entry', new_space_content_type_entry_path(space_id: @space, content_type_id: 1), class: 'pure-button pure-button-primary' %>
            <% end %>
        <hr>

        <% if @space.content_types.count > 0 %>
            <h3>Content Types</h3>
            <ul class="spaces-list">
                <% @space.content_types.each do |ct| %>
                    <li>
                        <%= link_to ct.name, space_content_type_path(space_id: ct.space.id, id: ct.id) %>
                        <ul class="actions">
                            <!-- TODO: Make this a Dropdown Element -->
                            <% if false %> <!-- commented out -->
                            <li>
                                <%= link_to edit_space_content_type_path(space_id: ct.space.id, id: ct.id) do %> 
                                    <%= fa_icon "gear", class: 'fa-fw' %>
                                <% end %>
                            </li>
                            <% end %> <!-- end commented code -->

                            <li>
                                <%= link_to new_space_content_type_entry_path(space_id: ct.space.id, content_type_id: ct.id) do %>
                                    <%= fa_icon "file", class: 'fa-fw', style: 'color: #0078E7' %>
                                <% end %>
                            </li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        <% else %>
            <p>No Content Types found.</p>
        <% end %>

    </div>
</div>

app/views/spaces/update.html.erb
<h1>Space#update</h1>
<p>Find me in app/views/space/update.html.erb</p>